---
name: Update dependent repositories
on:
  push:
    branches:
      - main
jobs:
  update-dependent-repositories:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' || github.event_name == 'push' }}
    uses: networkservicemesh/.github/.github/workflows/update-dependent-repositories-gomod.yaml@main
    with:
      dependent_repositories: |
        ["integration-k8s-packet",
        "integration-k8s-gke",
        "integration-k8s-aks",
        "integration-k8s-aws",
        "integration-interdomain-k8s"]
      base_repository: "networkservicemesh/integration-tests"
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
